name: go-package
run-name: ${github.actor}
on: 
  label:
    types:
     - created
  push: 
    branches: 
      - 'release/**'
    tags: 
      - v2
      - v1.*
  
jobs: 
 run-service: 
  runs-on: ubuntu-latest
  steps: 
    - uses: action/checkout/@v3
      with: 
      go-version: '1.17.6'
      repository: 
    -build: action/build
    -run: go run main.go
       
